fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: App\Types\RegistrationType
    from_email:
        address: "null"
        sender_name: "null"
